FROM --platform=linux rust:1.64.0 AS builder

RUN apt-get update
RUN apt-get install libusb-1.0-0-dev --yes

ENV LOCAL=/usr/local
ENV RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
ENV TMKMS_VERSION=v0.12.2

WORKDIR /root
RUN git clone --branch ${TMKMS_VERSION} https://github.com/iqlusioninc/tmkms.git
WORKDIR /root/tmkms
RUN cargo build --release --features=softsign

FROM --platform=linux ubuntu:22.04

COPY --from=builder /root/tmkms/target/release/tmkms ${LOCAL}/bin

ENTRYPOINT [ "tmkms" ]

# Create the image
# $ docker build -f Dockerfile-ubuntu-tmkms . -t tmkms_i
# To test only 1 command
# $ docker run --rm -it tmkms_i
# To build container
# $ docker create --name tmkms -i -v $(pwd)/docker/kms-alice:/root/tmkms tmkms_i
# $ docker start tmkms
# To run server on it
# $ docker exec -it tmkms start
# In other shell, to query it
# $ docker exec -it tmkms version